"""more charachters for settings

Revision ID: V1.0.2
Revises: V1.0.0
Create Date: 2024-11-06 14:33:30.129005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'V1.0.2'
down_revision: Union[str, None] = 'V1.0.0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'value',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=60),
               existing_comment='The value of the setting',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'value',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=20),
               existing_comment='The value of the setting',
               existing_nullable=False)
    # ### end Alembic commands ###
